---
name: build-release
on: 
  pull_request:
      branches:
        - main
      types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          make build-darwin-amd64
          make build-linux-amd64
          make build-linux-arm64
      - name: Set env
        run: echo "RELEASE_VERSION=$(./gobcrypt_linux_amd64 -v | awk '{print $3}' | sed 's/-.*//')" >> $GITHUB_ENV                         
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          tag_name: $RELEASE_VERSION
          files: |
            gobcrypt_darwin_amd64
            gobcrypt_linux_amd64
            gobcrypt_linux_arm64

...