---
name: test-lint
on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
      
    # Run vet & lint on the code
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
    
    # Run testing on the code
    - name: Run testing
      run: make test

    # Update go report
    - name: Update Go Report
      run: curl -X POST -F "repo=github.com/mijho/gobcrypt" https://goreportcard.com/checks

...